config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "restaurants#index"

  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews,
        -> { extending WithUserAssociationExtension },

            dependent: :destroy
  validates :name, length: { minimum: 3 }, uniqueness: true
  validates :user_id, length: { minimum: 1 }, allow_nil: true

  def average_rating
    self.reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user_id, length: { minimum: 1 }, allow_nil: true
  validates :restaurant_id, length: { minimum: 1 }, allow_nil: true

end

app/models/reviewed_restaurant.rb
class ReviewedRestaurant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  def owns_restaurant?(restaurant)
    self.restaurants.include? restaurant
  end

  def return_current_user
    unless current_user.nil?
      current_user
    end
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

  def create_with_user_foreign_key(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user_foreign_key!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end


  def build_review_with_user_foreign_key(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :user_id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_review_with_user_foreign_key(reviews_params, current_user)
    if @review.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

private

  def reviews_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/views/application/_header.erb
<% if !user_signed_in? %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% else %>
  <% unless current_user.image.nil? %>
    <%= image_tag current_user.image %>
    <% end %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>
<%= notice %>
<%= alert %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'header' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_user_header.erb
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>

app/views/restaurants/edit.erb
<%= form_for @restaurant, url:{action: "update"} do |f| %>
  <%= f.label :name, 'Restaurant name: '%>
  <%= f.text_field :name %>
  <%= f.label :description, 'Restaurant description: '%>
  <%= f.text_area :description %>
	<%= f.label :rating, 'Restaurant rating: '%>
  <%= f.number_field :rating, in: 0..5 %>
  <%= f.submit 'Update Restaurant' %>
<% end %>

app/views/restaurants/index.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<h2><%= link_to restaurant.name, restaurant_path(restaurant) %> <%=restaurant.rating%>/5</h2>
	<%end%>
<% else %>
<h1>No restaurants yet</h1>
<% end %>

<%= link_to 'Add a restaurant', new_restaurant_url %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>

  <% @restaurants.each do |restaurant| %>

    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <h4><%= restaurant.description %></h4>
  <% unless current_user.nil? %>
    <% if current_user.owns_restaurant?(restaurant) %>
      <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></h3>
    <% elsif !current_user.has_reviewed?(restaurant) %>
      <h3><%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <% end %>
  <% end %>

    _____________________________________________________
  <% end %>

<% else %>

  <p>"No restaurants yet"</p>

<% end %>

<%= link_to "Add a restaurant", controller: "restaurants", action: "new" %>

app/views/restaurants/new.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= form_for @restaurant, url:{action: "create"} do |f| %>
  <%= f.label :name, 'Restaurant name: '%>
  <%= f.text_field :name %>
  <%= f.label :description, 'Restaurant description: '%>
  <%= f.text_area :description %>
  <%= f.submit 'Add Restaurant' %>
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <!-- <%= f.hidden_field :user_id, :value => current_user.id%> -->
  <%= f.submit %>
<% end %>

app/views/restaurants/show.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.description %></p>
<p>Rating: <%= @restaurant.rating %>/5</p>
<% @reviews.each do |r| %>
  <div class="review">
    <p>Rated <%= r.rating %>/5</p>
    <p><%= r.comments %></p>
    <p>At <%= r.created_at %></p>
  </div>
<% end %>
<%= link_to 'Edit', edit_restaurant_url(@restaurant.id) %>
<%= link_to 'Delete', restaurant_url(@restaurant), method: :delete %>
<%= link_to 'Review', new_restaurant_review_path(@restaurant.id) %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.description %></h2>

<% if @reviews.none? %>
  <h3> Be the first to review <%= @restaurant.name %> </h3>
<% else%>
  <h3> Reviews of <%= @restaurant.name %> </h3>

  <h3> Average rating: <%= @restaurant.average_rating %> </h3>
  <ul>
    <% @reviews.each do |review |%>
    <% @reviewer = User.find(review.user_id) %>
    <li> Reviewed by <%= @reviewer.email %></li>
    <h4> Rating: <%= review.rating %></h4>
    <h4> Review: <%= review.thoughts %></h4>
    <% end %>
  </ul>
<% end %>

app/views/reviews/new.erb
<%= form_for [@restaurant,@review] do |f| %>
  <%= f.label :comments, 'Your comments: ' %>
  <%= f.text_area :comments %>
  <%= f.label :rating, 'Your rating: ' %>
  <%= f.number_field :rating, in: 0..5 %>
  <%= f.submit 'Review' %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <!-- <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.hidden_field :restaurant_id, :value => @restaurant.id%> -->
  <%= f.submit 'Leave Review' %>
<% end %>